### ISSUE TITLE
Google Drive sync does not work

### ISSUE THREAD

**Issue by timkgh** [anod/AppWatcher#94]
I gave it all permissions but still "Sync error" all the time.

**Comment by timkgh** [comment]
Ah I didn't know there was an app log.

```
02-01 06:54:21.930[4] [MAIN:2] PeriodicWork: Sync scheduled
02-01 06:54:21.865[4] [MAIN:2] PeriodicWork: Schedule sync in 2 hours (Keep existing)
02-01 06:54:16.313[4] [MAIN:2] PeriodicWork: Sync scheduled
02-01 06:54:16.232[4] [MAIN:2] PeriodicWork: Schedule sync in 2 hours (Keep existing)
02-01 06:53:18.889[6] 	at java.lang.Thread.run(Thread.java:920)
02-01 06:53:18.889[6] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-01 06:53:18.889[6] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-01 06:53:18.889[6] 	at lb.b1.run(DispatchedTask.kt:22)
02-01 06:53:18.889[6] 	at kotlin.coroutines.jvm.internal.a.resumeWith(ContinuationImpl.kt:3)
02-01 06:53:18.889[6] 	at j4.d$c.invokeSuspend(DriveService.kt:6)
02-01 06:53:18.889[6] 	at com.google.api.client.googleapis.services.b.execute(AbstractGoogleClientRequest.java:1)
02-01 06:53:18.889[6] 	at com.google.api.client.googleapis.services.b.executeUnparsed(AbstractGoogleClientRequest.java:1)
02-01 06:53:18.889[6] 	at com.google.api.client.googleapis.services.b.executeUnparsed(AbstractGoogleClientRequest.java:3)
02-01 06:53:18.889[6] 	at x7.o.b(HttpRequest.java:102)
02-01 06:53:18.889[6] 	at com.google.api.client.googleapis.services.b$a.a(AbstractGoogleClientRequest.java:4)
02-01 06:53:18.889[6] 	at com.google.api.client.googleapis.services.json.b.newExceptionOnError(AbstractGoogleJsonClientRequest.java:1)
02-01 06:53:18.889[6] 	at com.google.api.client.googleapis.services.json.b.newExceptionOnError(AbstractGoogleJsonClientRequest.java:2)
02-01 06:53:18.889[6] }
02-01 06:53:18.889[6]   "message" : "The resource body includes fields which are not directly writable."
02-01 06:53:18.889[6]   } ],
02-01 06:53:18.889[6]     "reason" : "fieldNotWritable"
02-01 06:53:18.889[6]     "message" : "The resource body includes fields which are not directly writable.",
02-01 06:53:18.889[6]     "domain" : "global",
02-01 06:53:18.889[6]   "errors" : [ {
02-01 06:53:18.889[6]   "code" : 403,
02-01 06:53:18.889[6] {
02-01 06:53:18.889[6] POST https://www.googleapis.com/drive/v3/files
02-01 06:53:18.889[6] Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
02-01 06:53:18.889[6] 	at kotlinx.coroutines.scheduling.a$c.run(CoroutineScheduler.kt:1)
02-01 06:53:18.889[6] 	at kotlinx.coroutines.scheduling.a$c.m(CoroutineScheduler.kt:4)
02-01 06:53:18.889[6] 	at kotlinx.coroutines.scheduling.a$c.c(CoroutineScheduler.kt:4)
02-01 06:53:18.889[6] 	at kotlinx.coroutines.scheduling.a.B(CoroutineScheduler.kt:1)
02-01 06:53:18.889[6] 	at lb.b1.run(DispatchedTask.kt:21)
02-01 06:53:18.889[6] 	at kotlin.coroutines.jvm.internal.a.resumeWith(ContinuationImpl.kt:10)
02-01 06:53:18.889[6] 	at lb.a.resumeWith(AbstractCoroutine.kt:3)
02-01 06:53:18.889[6] 	at lb.c3.Q0(CoroutineContext.kt:11)
02-01 06:53:18.889[6] 	at kotlin.coroutines.jvm.internal.a.resumeWith(ContinuationImpl.kt:3)
02-01 06:53:18.889[6] 	at com.anod.appwatcher.backup.gdrive.GDriveSync$b.invokeSuspend(GDriveSync.kt:10)
02-01 06:53:18.889[6] }
02-01 06:53:18.889[6]   "message" : "The resource body includes fields which are not directly writable."
02-01 06:53:18.889[6]   } ],
02-01 06:53:18.889[6]     "reason" : "fieldNotWritable"
02-01 06:53:18.889[6]     "message" : "The resource body includes fields which are not directly writable.",
02-01 06:53:18.889[6]     "domain" : "global",
02-01 06:53:18.889[6]   "errors" : [ {
02-01 06:53:18.889[6]   "code" : 403,
02-01 06:53:18.889[6] {
02-01 06:53:18.889[6] POST https://www.googleapis.com/drive/v3/files
02-01 06:53:18.889[6] com.anod.appwatcher.backup.gdrive.GDriveSync$SyncError: 403 Forbidden
02-01 06:53:18.889[6] }
02-01 06:53:18.889[6]   "message" : "The resource body includes fields which are not directly writable."
02-01 06:53:18.889[6]   } ],
02-01 06:53:18.889[6]     "reason" : "fieldNotWritable"
02-01 06:53:18.889[6]     "message" : "The resource body includes fields which are not directly writable.",
02-01 06:53:18.889[6]     "domain" : "global",
02-01 06:53:18.889[6]   "errors" : [ {
02-01 06:53:18.889[6]   "code" : 403,
02-01 06:53:18.889[6] {
02-01 06:53:18.889[6] POST https://www.googleapis.com/drive/v3/files
02-01 06:53:18.889[6] [MAIN:2] b.f: 403 Forbidden
02-01 06:53:18.887[6] }
02-01 06:53:18.887[6]   "message" : "The resource body includes fields which are not directly writable."
02-01 06:53:18.887[6]   } ],
02-01 06:53:18.887[6]     "reason" : "fieldNotWritable"
02-01 06:53:18.887[6]     "message" : "The resource body includes fields which are not directly writable.",
02-01 06:53:18.887[6]     "domain" : "global",
02-01 06:53:18.887[6]   "errors" : [ {
02-01 06:53:18.887[6]   "code" : 403,
02-01 06:53:18.887[6] {
02-01 06:53:18.887[6] POST https://www.googleapis.com/drive/v3/files
02-01 06:53:18.887[6] [56] GDriveSync: Sync failed: 403 Forbidden
02-01 06:53:18.052[4] [56] GDriveSync: Sync to remote applist.json
```

**Comment by anod** [comment]
I've published a new beta 1.4.9, which should help. try to "turn off" / "turn on" and then "sync now"

**Comment by timkgh** [comment]
Works now, thank you.
